name: Self check

on:
  push:
    branches:
      - main
      - master
  pull_request: []

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.3.4.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: "Build"
        run: "make"
      - name: "Self check"
        run: |
          if [ $(make gradualize | wc -l) -lt 100 ]; then
            echo "ok, self reported errors are in check"
            exit 0
          else
            echo "we've regressed, failing the job"
            exit 1
          fi
